[book]
authors = ["Andrii"]
language = "en"
multilingual = false
src = "src"
title = "Modern Firmware Development"

[output.html]
git-repository-url = "https://github.com/w1ne/ModernFirmwareDevelopment"

[preprocessor.mermaid]
command = "mdbook-mermaid"
